# Site settings
title: Coro da Achada
#email: caue@cregox.com
# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coroachada.github.io" # the base hostname & protocol for your site
prose_url: http://prose.io/#coroachada/coroachada.github.io/edit/master
twitter_username: coroachada
github_username:  coroachada


# Build settings
markdown: kramdown
